# Generated by Django 2.2.2 on 2019-06-16 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('nickname', models.CharField(db_index=True, max_length=1000, verbose_name='Имя пользователя')),
                ('team', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Команда')),
                ('link_manager', models.CharField(blank=True, max_length=4000, null=True, verbose_name='Ссылка на пользователя')),
                ('link_team', models.CharField(blank=True, max_length=4000, null=True, verbose_name='Ссылка на команду')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managers.Gender', verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Менеджер',
                'verbose_name_plural': 'Менеджеры',
                'ordering': ['nickname'],
            },
        ),
    ]
