# Generated by Django 2.2.2 on 2019-07-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0002_manager2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('chemp', models.CharField(db_index=True, max_length=1000, verbose_name='Чемпионат')),
                ('chemp_link', models.CharField(db_index=True, max_length=1000, verbose_name='Ссылка на чемпионат')),
                ('div', models.CharField(db_index=True, max_length=1000, verbose_name='Дивизион')),
                ('div_link', models.CharField(db_index=True, max_length=1000, verbose_name='Ссылка на дивизион')),
                ('command', models.CharField(db_index=True, max_length=1000, verbose_name='Команда')),
                ('command_link', models.CharField(db_index=True, max_length=1000, verbose_name='Ссылка на команду')),
            ],
            options={
                'verbose_name': 'Чемпионат',
                'verbose_name_plural': 'Чемпионаты',
            },
        ),
        migrations.AddField(
            model_name='manager2',
            name='link_photo',
            field=models.CharField(blank=True, max_length=4000, null=True, verbose_name='Ссылка на фото'),
        ),
    ]
