# Generated by Django 2.2.2 on 2019-07-19 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0003_auto_20190718_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager2',
            name='team_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managers.Chemps', verbose_name='Команда'),
        ),
    ]
