# Generated by Django 2.2.2 on 2019-07-19 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0004_manager2_team_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager2',
            name='link_team',
        ),
        migrations.RemoveField(
            model_name='manager2',
            name='team_id',
        ),
        migrations.AlterField(
            model_name='manager2',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managers.Chemps', verbose_name='Команда'),
        ),
    ]
