# Generated by Django 2.2.2 on 2019-07-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0005_auto_20190719_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(db_index=True, max_length=1000, verbose_name='Имя пользователя')),
                ('link', models.CharField(blank=True, max_length=4000, null=True, verbose_name='Ссылка на пользователя')),
            ],
        ),
    ]
