# Generated by Django 2.2.2 on 2019-07-20 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0006_managerlink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager2',
            options={'ordering': ['manager'], 'verbose_name': 'Менеджер', 'verbose_name_plural': 'Менеджеры'},
        ),
        migrations.RemoveField(
            model_name='manager2',
            name='link_manager',
        ),
        migrations.RemoveField(
            model_name='manager2',
            name='nickname',
        ),
        migrations.AddField(
            model_name='manager2',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managers.ManagerLink', verbose_name='Пользователь'),
        ),
    ]
