# Generated by Django 2.2.2 on 2019-07-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0007_auto_20190720_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managerlink',
            options={'ordering': ['nickname'], 'verbose_name': 'Ссылки на менеджеров', 'verbose_name_plural': 'Ссылки на менеджеров'},
        ),
    ]
