# Generated by Django 2.2.2 on 2019-07-25 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0008_auto_20190721_0844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
