# Generated by Django 2.2.2 on 2019-07-25 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0009_delete_manager'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manager2',
            new_name='Manager',
        ),
    ]
