# Generated by Django 2.2.2 on 2019-07-25 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0010_auto_20190725_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Divs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('name', models.CharField(db_index=True, max_length=1000, verbose_name='Дивизион')),
                ('link', models.CharField(db_index=True, max_length=1000, verbose_name='Ссылка на дивизион')),
                ('sort', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Дивизион',
                'verbose_name_plural': 'Дивизионы',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('name', models.CharField(db_index=True, max_length=1000, verbose_name='Команда')),
                ('link', models.CharField(db_index=True, max_length=1000, verbose_name='Ссылка на команду')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='chemps',
            options={'ordering': ['name'], 'verbose_name': 'Чемпионат', 'verbose_name_plural': 'Чемпионаты'},
        ),
        migrations.RenameField(
            model_name='chemps',
            old_name='chemp_link',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='chemps',
            old_name='chemp',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='chemps',
            name='command',
        ),
        migrations.RemoveField(
            model_name='chemps',
            name='command_link',
        ),
        migrations.RemoveField(
            model_name='chemps',
            name='div',
        ),
        migrations.RemoveField(
            model_name='chemps',
            name='div_link',
        ),
        migrations.AlterField(
            model_name='manager',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managers.Teams', verbose_name='Команда'),
        ),
        migrations.AddField(
            model_name='teams',
            name='chemp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managers.Chemps', verbose_name='Чемпионат'),
        ),
        migrations.AddField(
            model_name='teams',
            name='div',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managers.Divs', verbose_name='Дивизион'),
        ),
        migrations.AddField(
            model_name='divs',
            name='chemp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='managers.Chemps', verbose_name='Чемпионат'),
        ),
    ]
