# Generated by Django 2.2.2 on 2019-07-25 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managers', '0011_auto_20190725_0839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='chemp',
        ),
    ]
